spring:
  datasource:
    url: jdbc:mysql://localhost:3315/altenshop
    username: root
    password: dfepass
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      max-lifetime: 9999
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    
server:
  port: 8095
  error:
    whitelabel:
      enabled: false
    path: /api/error
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 18144000000 # 30 jours
      refresh-token: 
        expiration: 604800000 # 7 jours
  mode: dev
  